### PR TITLE
fix aui/auibook.py for issue #358

### LINKED ISSUE #358: size problem with agw.auibook
in aui_notebook demo, if you drag a tab and drop it near a border of the auibook you get two visible book pages as expected. But in Classic they have the same size while in Phoenix (latest snapshot and a2) the new one is very narrow. Comparing auibook.py files of Classic and Phoenix I can't see any explicit statement on sizes that could explain this (python 3.5-64, win7)

### PR DESCRIPTION
**Pull request by infinity77**
Fixes #358

### CODE REVIEW

**Comment by swt2c** [comment]
Maybe we should just make `Index` a property?  It seems that Robin has done that for most of the wrapped widgets, so maybe it would be good to do so to be similar to `wx.ListEvent`, for example?

**Comment by infinity77** [comment]
I still have a very lot to learn on Git... this pull request was supposed to fix only the auibook problem, the Index issue was another fix that I put in the ULC demo on my fork but somehow ended up here... how do I separate them?

Anyway, yes, Index should be a property of UltimateListEvent too. I’ll push a fix later.

**Comment by swt2c** [comment]
> I still have a very lot to learn on Git... this pull request was supposed to fix only the auibook problem, the Index issue was another fix that I put in the ULC demo on my fork but somehow ended up here... how do I separate them?

It looks like you made multiple commits in your master branch, then you submitted a PR from that branch.  Generally, the workflow I use is:
1) Start in updated master branch
2) Create topic branch for fix A
3) Fix one bug and then commit
4) Push topic branch and submit PR
5) Switch back to master branch
6) Create topic branch for fix B
...etc.

**Comment by RobinD42** [comment]
@infinity77, there is a bit about working with git and contributing to the project here: https://wxpython.org/pages/contributor-guide/

I know that in the past, at least, that you favored GUI tools for interacting with SVN.  I recommend SourceTree, in addition to the command-line. It does a good job of insulating you from the tricky parts or the things that are not used enough to be fresh in the memory all the time. It also has the ability to initiate submitting a branch as a PR, which I find very handy.

**Comment by Metallicow** [comment]
@infinity77 If you are on Windows or MacOSX, the Github for Windows GUI made by github is fairly straightforward. It has a tutorial built in also.
https://desktop.github.com/

**Comment by infinity77** [comment]
@swt2c, thanks for the suggestion. I still have messed up with the latest pull request and on my “documentation” branch. I’ve tried to revert the changes and create proper branches, but git tells me “nothing to revert”. Yeah, right. Even With all its flaws, I miss SVN. What I’m doing now is this ridiculous procedure:

1. Create a new branch from my fork
2. Make changes to the code
3. Can’t test the changes done as the git folder doesn’t live in site-packages, and even if it did, the “wx” folder doesn’t contain any dll and it lives parallel to the other Phoenix folders (sphinxtools, etg, etc...)
3. Copy the modified files into site-packages
4. Test with the demo
5. If everything works, commit push pull (!!!!)
6. Login into github, make a pull request - up to now I my screwed up ratio is at 100%

Hopefully Robin will be able to merge all the changes I’ve made, 4 issues should be fixed.

**Pull request merged**
