### PR TITLE
Fixes issue #1574: Still missing close for open, replace with a "with" block

### LINKED ISSUE #1574: Still Missing close for open, replace with a "with" block
The file opened in the line mentioned here:

https://github.com/wxWidgets/Phoenix/blob/f1aaa8b6d34ab476722d642c29d041675dfae5f9/demo/Main.py#L349

is missing a close statement.
If the "close()" call is missing after a "open(filename)" call, the filename isn't guaranteed to be closed before the interpreter exits.
This is generally a bad practice as explained here: https://stackoverflow.com/questions/7395542/is-explicitly-closing-files-important

Should also replace "fid=open(filename) fid.close()" statements for files with the safer
"with open(filename) as fid:" blocks. See PEP343: https://www.python.org/dev/peps/pep-0343/

These issues was addressed in the issue #1571 and partly solved with commit [7a05d20](https://github.com/wxWidgets/Phoenix/commit/7a05d20d829869f435aeef59f032e275d783eee4) (pullrequest #1572).
However, these issues still occur sevaral places throughout the code base, eg.:

https://github.com/wxWidgets/Phoenix/blob/f1aaa8b6d34ab476722d642c29d041675dfae5f9/demo/Main.py#L967

https://github.com/wxWidgets/Phoenix/blob/f1aaa8b6d34ab476722d642c29d041675dfae5f9/demo/Main.py#L1100

https://github.com/wxWidgets/Phoenix/blob/f1aaa8b6d34ab476722d642c29d041675dfae5f9/demo/Main.py#L1178

https://github.com/wxWidgets/Phoenix/blob/f1aaa8b6d34ab476722d642c29d041675dfae5f9/demo/Main.py#L1676

https://github.com/wxWidgets/Phoenix/blob/f1aaa8b6d34ab476722d642c29d041675dfae5f9/demo/Main.py#L2534

https://github.com/wxWidgets/Phoenix/blob/f1aaa8b6d34ab476722d642c29d041675dfae5f9/etgtools/extractors.py#L819

https://github.com/wxWidgets/Phoenix/blob/f1aaa8b6d34ab476722d642c29d041675dfae5f9/etgtools/extractors.py#L1473

https://github.com/wxWidgets/Phoenix/blob/f1aaa8b6d34ab476722d642c29d041675dfae5f9/etgtools/extractors.py#L1619

### PR DESCRIPTION
**Pull request by pbrod**
Fixes #1574 

Adding missing close for open and replaced "fid=open(filename) fid.close()"
statements with the safer "with open(filename) as fid:" blocks.

Also removed unnecessary "try: ... finally: pass" statements

### CODE REVIEW

**Comment by RobinD42** [comment]
Note that using "Fixes issue #XXXX" does not trigger auto-closing. You need to use "Fixes #XXXX"

**Comment by pbrod** [comment]
Ok. Now I have changed the commit message to include "Fixes #1574".

**Comment by Metallicow** [comment]
Yes the message is sorta built in for you to use it lol...

**Comment by Metallicow** [comment]
Upon issueing a PulReq it has a part in it that says Fixes#  somenumber. use that instead and give your titles more meaning as to what you have done.

**Comment by Metallicow** [comment]
Excuse me for being rude if it sounds that way...

But if I open a issue that say "There is a typo in Yadayada.py"
when I open a Pull Request to solve the issue it has a line like Fixes#whatevermyissuenumbermaybe
Upon pulling those changes in it will automatically close that issuenumber. 
This is a **_feature_** of github.

**Comment by Metallicow** [comment]
It also may say Closes#yaya123

**Comment by RobinD42** [comment]
> Ok. Now I have changed the commit message to include "Fixes #1574".

It doesn't need to be in the commit message, just the PR description text, which I've already changed.

**Pull request merged**
