### PR TITLE
Update wxWidgets to 3.1.7

### PR DESCRIPTION
**Pull request by swt2c**

### CODE REVIEW

**Comment by swt2c** [comment]
@RobinD42 any objections?

**Comment by DietmarSchwertberger** [comment]
@swt2c : I have opened a PR #2181 to add `EVT_GRID_ROW_MOVE`  to the grid etg and test file.
Maybe, you just want to include these modifications to your PR and I will close mine.

**Comment by RobinD42** [comment]
I'll review this evening

**Comment by RobinD42** [comment]
Replaced by #2183

**Pull request closed without merging**
