### PR TITLE
Update wxWidgets to v3.2.5.

### PR DESCRIPTION
**Pull request by jmoraleda**
Update wxWidgets to v3.2.5. Add support for new API MSW-only Accessibility related methods in wxWidgets. See [relevant wxWidgets commit](https://github.com/wxWidgets/wxWidgets/commit/81e9373efa99aede6a9cd6d280b5671fe8e44be3).

### CODE REVIEW

**Comment by swt2c** [comment]
Thanks, was going to do this myself soon.  Let's see how the CI does...

**Comment by swt2c** [comment]
Actually yeah I think we probably want Dietmar's version of the accessibility stuff.  So let's drop that from this one and just update to wx 3.2.5 (or I can do that).

**Comment by jmoraleda** [comment]
What about we do it in two phases? This PR, does the minimal update to 3.2.5 (without the minimal `windows.h` stuff that I have here it won't compile on GTK or Mac). And then we can do the the other PR to actually add Accessibility support. What do you think?

**Comment by swt2c** [comment]
Can you update this to include Dietmar's changes?  If not, I'll do it.

**Comment by jmoraleda** [comment]
Scott, thank you for offering to help. Please, go ahead and make the changes. Either as part of this PR, or merge this PR and then immediately add Dietmars'. As you think best.

I am not comfortable enough with sip to make Dietmar's changes: I was able to make the changes here because the new functions had identical signatures to `GetAccessible` which was already handled in sip.

**Comment by swt2c** [comment]
You don't have to know anything about sip, just how to copy and paste.  Anyway, I merged your changes with Dietmar's and pushed them (I couldn't push to your branch even though github says I should be able to edit your PR).

**Comment by jmoraleda** [comment]
Thank you, Scott.

**Pull request closed without merging**
