### PR TITLE
[ULC] add method GetCheckedItemCount

### PR DESCRIPTION
**Pull request by topic2k**
Added a method to get the number of checked items.

### CODE REVIEW

**Comment by Metallicow** [comment]
@topic2k Note: returning a len for a list comp I'm pretty sure would be a lot faster. Also would be a one-liner.

```python
        GetLine = self.GetLine  # local optimization
        return len([line for line in range(self.GetItemCount()) if GetLine(line).IsChecked(col)])
```
Haven't timeit tested but it is just a simple for loop that could look like this.

**Comment by topic2k** [comment]
@Metallicow, for me it makes no big difference (maybe i'm doing the tests wrong, never used timeit before). Most times your version is a little faster, sometimes mine.

I've attached my [test app](https://github.com/wxWidgets/Phoenix/files/4638564/ulc-speedtest.py.txt) (added .txt to the filename, as .py files are not allowed for upload) and replaced `GetCheckedItemCount` with this code:

<details>
<summary>GetCheckedItemCount with timeit</summary>

```python

    def GetCheckedItemCount(self, col=0):
        """
        Returns the number of checked items in the given column.

        :param col: an integer specifying the column index.
        :returns: the number of checked items.
        :rtype: int
        """

        import timeit

        def cnt1():
            countChkd = 0
            get_line = self.GetLine
            for line in range(self.GetItemCount()):
                if get_line(line).IsChecked(col):
                    countChkd += 1
            return countChkd

        def cnt2():
            GetLine = self.GetLine  # local optimization
            return len([line for line in range(self.GetItemCount()) if GetLine(line).IsChecked(col)])

        print("timeit cnt1(): ", timeit.timeit(stmt="cnt1()", number=1, globals=locals()))
        print("timeit cnt2(): ", timeit.timeit(stmt="cnt2()", number=1, globals=locals()))
        print()

        return cnt2()
```
</details>

 I run the test on Python 3.8.0 (default, Oct 15 2019, 09:10:20) [GCC 9.2.1 20191008] on linux and wxPython 4.1.0 gtk3 (phoenix) wxWidgets 3.1.4

**Comment by Metallicow** [comment]
Well for what its worth it appears if ya want more speed the thing to do would be to refactor/optimize the whole UltimateListCtrl. Most of the agw widgets are pure python, so anywhere things could be pushed into C would make it definitely faster.
It appears only the local opt did very little. also it is questionable if this function would get run more than once.

I see your speed issue haha... Sorry to say agw aui sucks like this too.
I'd say what you wrote is fine for now(add the local opt in), but if you really want to squeeze all the performance you can out of it, a rewrite/refactor would be in order, which would be a lot more work and testing each function for all possible bottlenecks. If the whole file was optimized for speed you would sacrifice some readability and would have to duplicate some code also since function calls are expensive.

Anyhow here is my sample results. I tried testing against count also, tho it didnt make any improvement.

```
wxPython 4.0.7.post2 msw (phoenix) wxWidgets 3.0.5 Scintilla 3.21
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:19:08) [MSC v.1500 32 bit (Intel)] on win32
Timeit Test - 1000 times
Test1:[22.47498697548353, 22.43635968767434, 22.463036032237568]
Test2:[22.1063757112166, 22.100655598119886, 22.27809651977529]
Test3:[22.121768246947283, 22.159043612526688, 22.160652946004006]

Winner: Test2
Loser: Test1
```
<details>
    <summary>Collapsible Content - timeit sample with added ulc stuff</summary>

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Imports ---------------------------------------------------------------------
# -Python Imports.
import os
import sys
import timeit

# -wxPython Imports.
import wx
from wx.lib.embeddedimage import PyEmbeddedImage

# test widget
from wx.lib.agw import ultimatelistctrl as ulc
ULC_KIND_NORMAL = 0  # A normal item
ULC_KIND_CHECKBOX = 1  # checkbox-like item
ULC_KIND_RADIO = 2  # A radiobutton-type item
ULC_COUNTER_IN_HEADER = 0x100000000


clock16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABK0lEQVR4AaWTPWqEUBSFAwMp"
    "ZwsTsEk19fRuwZVkC2JnI9hZiUKwVCuF1LbWbiClYKFGlRu/QEAmczPFHLjwePeco/fnPV3h"
    "sMVxi9MW5y0uBGfuyP1wFDxv8WIYxptlWR+2bX8mSfJFcOaOHBy4t8Svpmm+B0HQNU0jbdtK"
    "XddSVZVM0yTckYMDd29ywJVEURQLwnVdBYRhKJ7nyTAMwh05OHDR/JZz5Ndwh7BHHMfi+75g"
    "AAAcuGjQYnCiPn6Rr9wzgAMXDVoMzjQJZ3DPAMBFgxaDC50ex1GuEUWRuK4rfd/LHnDRoP3X"
    "oCxLcRxH8jyXeZ41A70ExpdlGSaSpqksy3KrBL2JABFiRtp13Z8mKmNUoIxRXaQ99EXSV5lm"
    "EZy1VX78MT38nL8BuoU1fzYVzjQAAAAASUVORK5CYII=")


class TimeitPanel(wx.Panel):
    def __init__(self, parent, id=wx.ID_ANY,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.BORDER_SUNKEN, name='panel'):
        wx.Panel.__init__(self, parent, id, pos, size, style, name)

        # Add testwidget to timeit sample---------
        self.testwidget = ulc.UltimateListCtrl(self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, style=0,
                                               agwStyle=ULC_COUNTER_IN_HEADER | ulc.ULC_REPORT | ulc.ULC_NO_HIGHLIGHT | ulc.ULC_AUTO_CHECK_CHILD)
        # choices=None,
        # columns=None,
        self.testwidget.Freeze()
        choices = ["item number %d" % idx for idx in range(1000)]
        columns=['']

        info = ulc.UltimateListItem()
        info.SetMask(
            ulc.ULC_MASK_TEXT |
            ulc.ULC_MASK_KIND |
            ulc.ULC_MASK_FORMAT
        )
        info.SetText(columns[0])
        info.SetAlign(ulc.ULC_FORMAT_LEFT)
        info.SetKind(ULC_KIND_CHECKBOX)
        self.testwidget.InsertColumnInfo(0, info)
        self.testwidget.SetColumnWidth(0, ulc.ULC_AUTOSIZE_FILL)

        AddChoice = self.AddChoice
        [AddChoice(choice, item_data=choice) for choice in choices]
        self.testwidget.Thaw()
        #-----------------------------------------

        self.rb = wx.RadioBox(self, wx.ID_ANY, 'Number of times to test',
                              choices=('1', '10', '42', '100', '1000',
                                       '10000', '100000', '1000000'),
                              majorDimension=4,
                              style=wx.RA_SPECIFY_COLS)
        self.rb.SetSelection(2)

        self.b1 = wx.Button(self, wx.ID_ANY, 'timeit')
        self.b1.Bind(wx.EVT_BUTTON, self.OnRunTheTimeitTests)

        vbSizer = wx.BoxSizer(wx.VERTICAL)
        vbSizer.Add(self.testwidget, 1, wx.EXPAND | wx.ALL, 5)
        vbSizer.Add(self.rb, 0, wx.EXPAND | wx.ALL, 5)
        vbSizer.Add(self.b1, 0, wx.EXPAND | wx.ALL, 5)
        self.SetSizer(vbSizer)


    # ulc helper
    def AddChoice(self, choice, checked=False, item_data=None):
        idx = self.testwidget.GetItemCount()
        new_item = ulc.UltimateListItem()
        new_item.SetId(idx)
        new_item.SetColumn(0)
        new_item.SetKind(ULC_KIND_CHECKBOX)
        new_item.Check(checked)
        new_item.SetState(ulc.ULC_STATE_FOCUSED)
        new_item.SetPyData(item_data)
        new_item.SetText(choice)
        self.testwidget.InsertItem(new_item)
        # self._dirty = True
        return idx

    def OnRunTheTimeitTests(self, event=None):
        """
        Explain a bit about the tests being performed HERE.
        Ex: local vs. global access time, considering dots kill performance.
        """
        # - Add Some Tests. 1 or more tests supported.
        def Test1():
            countChkd = 0
            ## get_line = self.testwidget.GetItem
            for line in range(self.testwidget.GetItemCount()):
                ## if get_line(line).IsChecked():
                if self.testwidget.GetItem(line).IsChecked():
                    countChkd += 1
            ##print(countChkd)
            return countChkd
        def Test2():
            GetLine = self.testwidget.GetItem  # local optimization
            ##print(len([line for line in range(self.testwidget.GetItemCount()) if GetLine(line).IsChecked()]))
            return len([line for line in range(self.testwidget.GetItemCount()) if GetLine(line).IsChecked()])
        def Test3():
            GetLine = self.testwidget.GetItem  # local optimization
            ##print(len([line for line in range(self.testwidget.GetItemCount()) if GetLine(line).IsChecked()]))
            return [GetLine(line).IsChecked() for line in range(self.testwidget.GetItemCount())].count(True)

        # - Prepare all the data for the Tests before testing.
        theLocals = locals()
        sortedLocals = sorted(list(theLocals.values()), key=str)
        allTestsTuple = tuple(sortedLocals)

        # - Define how many times we want to run the tests.
        timeitThisNumberTimes = int(self.rb.GetStringSelection())

        # - Do the actual testing and print out the individual results.
        print('')
        print('-' * 42)
        print('Timeit Test')

        testResultsDict = {}
        testResultsList = []
        for test in allTestsTuple:
            if not hasattr(test, '__call__'):
                continue
            testResults = timeit.repeat(test, number=timeitThisNumberTimes)
            print('%s:%s' % (test.__name__, testResults))
            testResultsList.append(testResults)
            testResultsDict['%s' % testResults] = test.__name__

        # Now that the testing is over, lets figure out the winners and losers.
        print('')
        winner = min(testResultsList)
        loser = max(testResultsList)
        print('Winner: %s' % testResultsDict['%s' % winner])
        print('Loser: %s' % testResultsDict['%s' % loser])


class TimeitFrame(wx.Frame):
    def __init__(self, parent, id=wx.ID_ANY, title=wx.EmptyString,
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.DEFAULT_FRAME_STYLE | wx.STAY_ON_TOP,
                 name='frame'):
        wx.Frame.__init__(self, parent, id, title, pos, size, style, name)
        global gMainWin
        gMainWin = self
        panel = TimeitPanel(self)
        vbSizer = wx.BoxSizer(wx.VERTICAL)
        vbSizer.Add(panel, 1, wx.EXPAND | wx.ALL, 5)
        self.SetSizerAndFit(vbSizer)
        self.Centre()
        statusBar = self.CreateStatusBar()
        pyVER = '%d.%d.%d %s' % sys.version_info[:4]
        verInfo = 'wxPython %s running on Python %s' % (wx.version(), pyVER)
        statusBar.SetStatusText(verInfo, 0)
        self.Bind(wx.EVT_CLOSE, self.OnDestroy)


    def OnDestroy(self, event):
        self.Destroy()


class TimeitApp(wx.App):
    def OnInit(self):
        self.SetClassName('TimeitApp')
        self.SetAppName('TimeitApp')
        gMainWin = TimeitFrame(None)
        gMainWin.SetTitle('Timeit Test: ')
        gMainWin.SetIcon(clock16.GetIcon())
        self.SetTopWindow(gMainWin)
        gMainWin.Show()
        return True


if __name__ == '__main__':
    gApp = TimeitApp(redirect=False,
                     filename=None,
                     useBestVisual=False,
                     clearSigInt=True)

    gApp.MainLoop()

```
</details>

**Comment by topic2k** [comment]
Although it doesn't make a big difference, i changed to list comprehension as 'it looks nicer'. :smiley:

**Pull request merged**
