### PR TITLE
Add support to python only pdfviewer for displaying pdf files where not all pages are the same size

### PR DESCRIPTION
**Pull request by jmoraleda**
The current PDF viewer assumes all pages in the PDF document being displayed are of the same size. When this is not the case the PDF does not display correctly.

This PR refactors the viewer so that PDF documents containing pages of different sizes display correctly.

I have thoroughly tested this PR in GTK and MSW and have found it to produce the correct results and have performance comparable to the previous version including for larger documents.

### CODE REVIEW

**Comment by jmoraleda** [comment]
See review of this PR in https://github.com/wxWidgets/Phoenix/pull/2492#issuecomment-1858873301

**Comment by jmoraleda** [comment]
I wonder if we could merge this in. 

It has been reviewed thoroughly at See discussion and review of this PR in https://github.com/wxWidgets/Phoenix/pull/2492#issuecomment-1858873301. That was an alternative PR for the same feature, and as you can see on the comments, all reviewers including the proponent of that PR agreed that this one was a better implementation.

Furthermore it has been thoroughly tested for several months by many people as part of the wxPython-Meticy release:  https://pypi.org/project/wxPythonMeticy/

**Comment by jmoraleda** [comment]
@Infernio I noticed you worked on the python only pdfviewer recently. Could you by any chance test this PR and provide feedback? Thank you!

**Comment by Infernio** [comment]
I don't use the pure Python one, judt the PyMuPDF one. That said, from looking over the commit, it seems fine.

**Pull request merged**
