### PR TITLE
Use maxsize instead of maxint

### PR DESCRIPTION
**Pull request by balshetzer**
Python 3 no longer has sys.maxint

### CODE REVIEW

**Comment by balshetzer** [comment]
It turns out there are other reasons why this module doesn't work with python 3.

**Comment by wernerfb** [comment]
I started working on this yesterday, I think I have the Py3 issues done, but wanted to update the documentation and create a unittest before I do a PR.

**Comment by balshetzer** [comment]
Thanks for tackling this!

**Comment by wernerfb** [comment]
No problem, see #25

**Comment by RobinD42** [comment]
Superseded by #25

**Pull request closed without merging**
