### PR TITLE
_msw with Metafile and MetafileDC

### PR DESCRIPTION
**Pull request by DietmarSchwertberger**
added a MS Windows specific _msw module with Metafile and MetafileDC
added _media module with MediaCtrl (please note that for MediaCtrl events change 5c1f95bc71028e4562f847af56b815b2f13370a9 from wxWidgets is also required)
added support for Visual Studio 2015 (for Python 3.5, the Community Edition supports both 32 and 64 bit)
modified lib.activex for Phoenix

### CODE REVIEW

**Comment by DietmarSchwertberger** [comment]
Please note that for MediaCtrl events change 5c1f95bc71028e4562f847af56b815b2f13370a9 from wxWidgets is also required.

**Comment by RobinD42** [comment]
It's almost as if you read some hand-written notes about these modules and Py3.5 I've had sitting on my desk for what feels like forever. :-)  I'll probably tweak some things before merging, but thanks for all your work on this.

**Comment by DietmarSchwertberger** [comment]
Sorry for the mess. This was my first use of Git and basically, most is copied together from other modules, wxPython Classic and your "todo" notes...

**Comment by RobinD42** [comment]
No problem, everybody takes a little while and some trial/error to get to know how things work.  For future reference this would have been better submitted as multiple PRs, one for each grouping of changes.  (For example, _media, _msw, VisStudio2015, etc.)  That is basically how I have been approaching merging it.

Also, things like comments about needing other commits, or suggestions for possible better ways to do something would be better here in the PR comments rather than in the commit message.

**Comment by RobinD42** [comment]
Closing, as all has been done via other PRs

**Pull request closed without merging**
