### PR TITLE
Fix functions of the shell

### PR DESCRIPTION
**Pull request by komoto48g**
This PR fixes some functionality of the wx.py.shell.

There was a problem that the Shell.OnUpdateUI overrides the parent EditWindow.OnUpdateUI. Thus the brace-matching is not working. In addition, the wx.EVT_UPDATE_UI is bound to the shell without specifying id, so the event is frequently triggered each time the caret moves or blinks. To fix it, we should remove the handler `OnUpdateUI` and bind wx.EVT_UPDATE_UI to each context-menu id.

It also fixes tiny bugs of incorrect indentation when pasting "try-finally" code and when typing "with" statement.

### CODE REVIEW

**Comment by RobinD42** [comment]
Is there a reason `OnUpdateContextMenu` is only commented-out and not removed?

**Comment by komoto48g** [comment]
Hi, Robin
Thank you for the code reviwing. There is no special reason.
(I'm sorry for including plural changes in this PR)
Best regards

**Comment by RobinD42** [comment]
Okay. Please clean it up with an additional commit to your branch and then I'll merge it.

**Comment by komoto48g** [comment]
I pushed them on the same PR branch.

**Pull request merged**
