### PR TITLE
Admonish deprecations

### LINKED ISSUE #458: Sphinx Build fails with Extension error: cannot import name make_admonition
Operating system: Win 10

wxPython version: 4.0.0b2

Stock or custom build: Source Build

Python version: 2.7.13 & 3.6.0

Stock or custom build: Stock

Sphinx v1.6.3

Description of the problem:
Running:
`python build.py sphinx`

Gives:

> Will build using: "C:\Python27\python.exe"                                                                                              
> 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]                                                        
> Python's architecture is 32bit                                                                                                          
> cfg.VERSION: 4.0.0b2                                                                                                                    
>                                                                                                                                         
> Running command: sphinx                                                                                                                 
> sphinx-build -b html -d D:\Users\212303160\GitWorking\wxPhoenixSJB\docs\sphinx\build/doctrees . D:\Users\212303160\GitWorking\wxPhoenixS
> JB\docs\html                                                                                                                            
> Running Sphinx v1.6.3                                                                                                                   
> c:\python27\lib\site-packages\sphinx\util\compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be
>  removed in Sphinx 1.7, please use docutils' instead.                                                                                   
>   RemovedInSphinx17Warning)                                                                                                             
>                                                                                                                                         
> Extension error:                                                                                                                        
> Could not import extension availability (exception: cannot import name make_admonition)                                                 
> Command 'sphinx-build -b html -d D:\Users\212303160\GitWorking\wxPhoenixSJB\docs\sphinx\build/doctrees . D:\Users\212303160\GitWorking\w
> xPhoenixSJB\docs\html' failed with exit code 1.                                                                                         
> Finished command: sphinx (14.441s)   

Searching for the missing import revealed: https://github.com/spinus/sphinxcontrib-images/issues/41

Tried the work around and it works.
```
diff --git a/docs/sphinx/conf.py b/docs/sphinx/conf.py
index a0675dfc..8b338c56 100644
--- a/docs/sphinx/conf.py
+++ b/docs/sphinx/conf.py
@@ -14,7 +14,9 @@

 import sys, os
 from datetime import datetime
-
+from docutils.parsers.rst.directives.admonitions import BaseAdmonition
+from sphinx.util import compat
+compat.make_admonition = BaseAdmonition
 # If extensions (or modules to document with autodoc) are in another directory,
 # add these directories to sys.path here. If the directory is relative to the
 # documentation root, use os.path.abspath to make it absolute, like shown here.

```

### LINKED ISSUE #748: Documentation for deprecated items
**Operating system**: any
**wxPython version**: any
**Stock or custom build**: any
**Python version**: any
**Stock or custom build**: any

**Description of the problem**:

Some (most?) of the @depreacted tags in the wxWidgets interface docs do not indicate the version when the item was deprecated, and it appears we are blindly substituting the current wxPython version into the documentation items. This is not accurate in almost all cases, and will cause confusion.

Track down the code that is doing that and change it to leave out the version and just say that it was deprecated. It's probably using a ReST directive and if the version is not optional there then something creative may need to be done.

### PR DESCRIPTION
**Pull request by mesalu**
Fixes #748, #458

This PR will:
- [x] Remove blindly inserting wxPython-version into the deprecation warning
- [x] Convert stock deprecation directives to custom admonition
- [x] Style that admonition to be visually fitting

edit:
- [x] Fix double-deprecation directives in certain doc pages, such as wx.VScrolledWindow
- [x] Edit Docstrings guidelines page to reflect new admonition
- [x] Fix #458 while I'm at it

### CODE REVIEW

**Comment by mesalu** [comment]
Current example of progress:

screen shot 2018-02-21 at 3 40 05 pm

**Comment by mesalu** [comment]
I've fixed double deprecations locally and will include that in the next commit or two.

**Comment by mesalu** [comment]
Progress update:
screen shot 2018-02-22 at 3 46 44 pm

**Comment by mesalu** [comment]
Added tweak to docstring guidelines. 

Removing WIP tag.

**Comment by RobinD42** [comment]
LGTM

**Pull request merged**
