### PR TITLE
Begin playing with GitHub workflows

### PR DESCRIPTION
**Pull request by RobinD42**

### CODE REVIEW

**Comment by swt2c** [comment]
I was going to ask if you we could switch to GitHub.  :+1:

**Comment by swt2c** [comment]
Also, are you attached to using Buildbot, or can we move that to GitHub Actions, too?

**Comment by RobinD42** [comment]
> Also, are you attached to using Buildbot, or can we move that to GitHub Actions, too?

Yes, I plan on moving the nightly and release deployment to GH as well. I've got a skeleton of a plan for it, but there's still a ways to go.

**Comment by RobinD42** [comment]
This pull request has been mentioned on **Discuss wxPython**. There might be relevant details there:

https://discuss.wxpython.org/t/the-future-of-wxpython/36852/19

**Pull request merged**
