### PR TITLE
Fix some Py3 issues

### PR DESCRIPTION
**Pull request by wernerfb**
Some changes done to SVN which did not make it to Phoenix.

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
Looks good to me -- thanks!

I  don't have permission to merge, though.

**Comment by wernerfb** [comment]
Robin will get to it when he finds time:)

**Comment by wernerfb** [comment]
Tested this with the FC demo on Py2.7 and Py3.4 and with my own stuff but only on Windows.

**Comment by PythonCHB** [comment]
Thanks!

**Pull request merged**
