### PR TITLE
Fix pdfViewer for Python 3.10

### LINKED ISSUE #2226: Broken pdfviewer - TypeError
**Description of the problem**:
When wxPython **4.2.0** demo "PDFViewer" (uses PyMuPDF 1.20.1) is launched and any PDF file is loaded, then following exception is thrown out:

```
Traceback (most recent call last):
  File "C:\Programs\Python310\lib\site-packages\wx\core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Programs\Python310\lib\site-packages\wx\lib\pdfviewer\viewer.py", line 410, in Render
    self.pagebuffer = wx.Bitmap(self.pagebufferwidth, self.pagebufferheight)
TypeError: Bitmap(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
  overload 4: argument 2 has unexpected type 'float'
  overload 5: argument 1 has unexpected type 'int'
  overload 6: argument 2 has unexpected type 'float'
  overload 7: argument 1 has unexpected type 'int'
  overload 8: argument 1 has unexpected type 'int'
  overload 9: argument 1 has unexpected type 'int'
  overload 10: too many arguments
```

**Operating system**: M$ Windows 10
**wxPython version & source**:  wxPython 4.2.0 from pypi (official release)
**Python version & source**: Python 3.10.6 64-bit from python.org

It seems that some results of computations are float numbers instead of expected integers. When I have tried to fix the issue by this patch, it works fine now (just added conversions into integers):

Patch for file `wx\lib\pdfviewer\viewer.py`:
```

299c299
<             self.Scroll(0, pagenum*self.Ypagepixels/self.GetScrollPixelsPerUnit()[1] + 1)
---
>             self.Scroll(0, int(pagenum*self.Ypagepixels/self.GetScrollPixelsPerUnit()[1]) + 1)
356a357
> 
358c359
<             self.Ypagepixels = nhi
---
>             self.Ypagepixels = int(nhi)
360c361
<             self.Ypagepixels = nlo
---
>             self.Ypagepixels = int(nlo)

```

### PR DESCRIPTION
**Pull request by Infernio**
Needs `int`s instead of `float`s in these two places. Didn't notice any others, but there may be more.

Fixes #2226

### CODE REVIEW

**Comment by ayham-1** [comment]
This issue also happens with `wx.Bitmap`

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/wx/lib/pdfviewer/viewer.py", line 149, in OnIdle
    self.Render()
  File "/usr/lib/python3.11/site-packages/wx/lib/pdfviewer/viewer.py", line 410, in Render
    self.pagebuffer = wx.Bitmap(self.pagebufferwidth, self.pagebufferheight)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Bitmap(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'int'
  overload 3: argument 1 has unexpected type 'int'
  overload 4: argument 2 has unexpected type 'float'
  overload 5: argument 1 has unexpected type 'int'
  overload 6: argument 2 has unexpected type 'float'
  overload 7: argument 1 has unexpected type 'int'
  overload 8: argument 1 has unexpected type 'int'
  overload 9: argument 1 has unexpected type 'int'
  overload 10: too many arguments
```

This is the traceback for the example on the website [https://pythonhosted.org/wxPython/wx.lib.pdfviewer.html](https://pythonhosted.org/wxPython/wx.lib.pdfviewer.html).

Python version 3.11
Packages are the versions present in ArchLinux's AUR, wxpython 4.2.0-4 and pymupdf 1.22.3-1

**Review by ayham-1 — COMMENTED** [review]
I think all similar instances in that file should also be replaced.

**Comment by Infernio** [comment]
`wxpython 4.2.0-4` is not from the AUR, that's the official package (which doesn't have this fix). This fix is only in the master branch, which you can get [from the AUR](https://aur.archlinux.org/packages/wxpython-phoenix-git), but be aware that that PKGBUILD is pretty broken right now (see my comment on the page for some fixes).

**Comment by ayham-1** [comment]
My mistake. So the official `python-wxpython` package is the wxpython classic package? Will it receive this patch?

**Comment by Infernio** [comment]
It's Phoenix, but it tracks the latest *release* (i.e. 4.2.0), not the master branch. This is the case for all packages in Arch Linux - VCS packages that track a branch always end with `-git`, `-svn`, etc.. `python-wxpython` will receive this fix once the upstream (so this repo) cuts a new release.

**Pull request merged**
